### ISSUE TITLE
Storing Image

### ISSUE THREAD

**Issue by tonespy** [Triple-T/simpleprovider#14]
How can we store Image in the ContentProvider. I tried this, but not working 
```
@Column(Column.FieldType.BLOB)
        public static final String IMAGE = "image"; //objectId
```

**Comment by bhurling** [comment]
Blob is the way to go. You have to compress your bitmap into a byte array as described here: http://stackoverflow.com/a/9357943

**Comment by bhurling** [comment]
Nothing to fix here
