### ISSUE TITLE
Database Name

### ISSUE THREAD

**Issue by xtools-at** [Triple-T/simpleprovider#24]
Hi there,

I was wondering what's the name of the Database _simpleprovider_ creates, as i can't find it in the Docs. I have to override the query()-Method for In-App Search, so I can't rely on the Cursor returned by LoaderManager.

Many thanks in advance!

**Comment by bhurling** [comment]
It defaults to the name of your class that is subclassing `AbstractProvider` (all lowercase with .db suffix). You can override the default by overriding `getDatabaseFileName()`

**Comment by xtools-at** [comment]
perfect, thanks!!!!!!
